name: velo_workspace
description: A multi-package workspace for Velo state management solution and testing utilities.
version: 1.0.0
homepage: https://github.com/steve-nosse/velo
repository: https://github.com/steve-nosse/velo
issue_tracker: https://github.com/steve-nosse/velo/issues
documentation: https://github.com/steve-nosse/velo#readme
publish_to: 'none' # This is a workspace, not a publishable package

environment:
  sdk: "^3.8.1"
  flutter: ">=3.0.0"

# Workspace configuration
workspace:
  - packages/velo
  - packages/velo_test

funding:
  - https://github.com/sponsors/stevenosse

topics:
  - state-management
  - flutter
  - testing
  - workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0