name: velo
description: A simple and efficient state management solution for Flutter, inspired by flutter_bloc but keeping only the essentials.
version: 1.1.0
homepage: https://github.com/stevenosse/velo
repository: https://github.com/stevenosse/velo
issue_tracker: https://github.com/stevenosse/velo/issues
documentation: https://github.com/stevenosse/velo#readme
resolution: workspace

environment:
  sdk: '^3.8.1'
  flutter: ">=3.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://github.com/sponsors/stevenosse

topics:
  - state-management
  - flutter
  - cubit
  - valuenotifier
  - equatable

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0